# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-sun7i-ries
KERNEL_VERSION=3.4.103-11-ARCH

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
